### PR TITLE
add plot_npc and plot_active_latent_units

### PR DESCRIPTION
**Pull request by mk017**

### CODE REVIEW

**Comment by le-ander** [comment]
leander: check z / zmean defaul handling for VAEs

**Comment by le-ander** [comment]
> leander: check z / zmean defaul handling for VAEs

Done.

Now waiting for code cleanup form martins side.

**Review by le-ander — APPROVED** [review]

**Comment by le-ander** [comment]
@davidsebfischer I would like to merge this branch, however it says "Merging is blocked" above.

Does this have to do with the branch protection you enabled?

**Comment by davidsebfischer** [comment]
Thanks for the note, this is because of the required signed commits, this wouldn't be an issue if we merged via a dev branch as previously imagined, I am deactivating this for now again so that merging should be possible again.

**Pull request merged**
