### PR TITLE
Train fixes

### PR DESCRIPTION
**Pull request by davidsebfischer**

### CODE REVIEW

**Comment by le-ander** [comment]
suddenly the docs build CI jobs is failing with

```
Exception occurred:
  File "/home/runner/work/sfaira/sfaira/docs/conf.py", line 124, in setup
    app.add_stylesheet('css/custom.css')
AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
The full traceback has been saved in /tmp/sphinx-err-3xhte9a0.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
make: *** [Makefile:16: html] Error 2
Error: Process completed with exit code 2.
```

any idea where this is coming form @davidsebfischer @Zethson ?

**Comment by Zethson** [comment]
> suddenly the docs build CI jobs is failing with
> 
> ```
> Exception occurred:
>   File "/home/runner/work/sfaira/sfaira/docs/conf.py", line 124, in setup
>     app.add_stylesheet('css/custom.css')
> AttributeError: 'Sphinx' object has no attribute 'add_stylesheet'
> The full traceback has been saved in /tmp/sphinx-err-3xhte9a0.log, if you want to report the issue to the developers.
> Please also report this if it was a user error, so that a better error message can be provided next time.
> A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
> make: *** [Makefile:16: html] Error 2
> Error: Process completed with exit code 2.
> ```
> 
> any idea where this is coming form @davidsebfischer @Zethson ?

Replace `add_stylesheet` with `add_css_file()` and if you want to prevent such errors from occurring in the future you can pin the Sphinx version :)

**Comment by le-ander** [comment]
Thanks Lukas! So basically sphinx just release a new version which is immediately used by our CI, correct?

Would you recommend pinning this?

**Comment by Zethson** [comment]
> Thanks Lukas! So basically sphinx just release a new version which is immediately used by our CI, correct?
> 
> Would you recommend pinning this?



> Thanks Lukas! So basically sphinx just release a new version which is immediately used by our CI, correct?
> 
> Would you recommend pinning this?

Yes.

https://github.com/theislab/sfaira/blob/master/requirements.txt#L11

No specified version -> always install the latest one.

I always pin each and every version of my dependencies. You should especially consider pinning sensitive dependencies such as numpy, pandas and Scanpy. Else your distributed sfaira version might randomly break in a year from now or so you will be confused.

**Pull request merged**
