### PR TITLE
Feature/cli improvements (#350)

### PR DESCRIPTION
**Pull request by lauradmartens**
Points addressed from #350
* Added questionnaire which asks for gene symbol/Ensembl id
* "Year" is now formatted as an integer in `create-dataloader`
* changed data loader validation check to `gene_id_symbols_var_key` instead of `gene_id_symbol_var_key`
* changed all `cell_types_original_obs_key` to `cell_type_obs_key`
*  deprecated `DatasetGroup._unknown_celltype_identifiers`

### CODE REVIEW

**Comment by Zethson** [comment]
@lauradmartens Note that sfaira_questionary always returns:
`Union[str, bool]`

Think that you get the string from sfaira_questionary and then cast it to `int`

Comment about the CI done on MM

**Comment by lauradmartens** [comment]
@davidsebfischer, Lukas and I discussed that rather than changing year in the yaml, we could cast it to int when reading it from the yaml file. Would this be a good place to do so? https://github.com/theislab/sfaira/blob/9590015acbc4f84454d3d75ff03b191c2472a219/sfaira/data/dataloaders/base/dataset.py#L1963

**Comment by davidsebfischer** [comment]
> @davidsebfischer, Lukas and I discussed that rather than changing year in the yaml, we could cast it to int when reading it from the yaml file. Would this be a good place to do so?
> 
> https://github.com/theislab/sfaira/blob/9590015acbc4f84454d3d75ff03b191c2472a219/sfaira/data/dataloaders/base/dataset.py#L1963

Yes, but the conversion needs to happen in the first line of that setter because the value protection already checks for int. Also, all entries of year in all data loaders would have to be updated to string values then in this PR.

**Comment by davidsebfischer** [comment]
https://github.com/theislab/sfaira/pull/363#discussion_r707146048 is this addressed?

**Comment by lauradmartens** [comment]
we kept the `create-dataloader` as I changed it, so `Year` will be formatted as int already in the yaml then there is no need to change all dataloaders. For #363 should the default embedding key just be blank or something like "X_umap"?

**Comment by davidsebfischer** [comment]
>  For #363 should the default embedding key just be blank or something like "X_umap"?

Blank!

**Comment by lauradmartens** [comment]
@Zethson, does just setting the default to blank work with the way the questionnaire is built at the moment? I think it will always fill an empty string into the yaml, right?

**Comment by Zethson** [comment]
> @Zethson, does just setting the default to blank work with the way the questionnaire is built at the moment? I think it will always fill an empty string into the yaml, right?

cookiecutter always copies into the template exactly what we specify.
Assuming that

`empty_string = ""`

and in the template `{{ empty_string }}` you should not notice that anything was ever supposed to be copied there.

Now if `empty_string = " "`

There would be a space at the position.

**Comment by davidsebfischer** [comment]
@Zethson can you accept the review and merge once this is done?

**Review by Zethson — APPROVED** [review]
LGTM

**Comment by davidsebfischer** [comment]
Great, thank for reviewing, @Zethson, and thanks for pointing this changes out and addressing them, @lauradmartens!

**Pull request merged**
