### PR TITLE
Rewrite test_store.py script

### PR DESCRIPTION
**Pull request by felix0097**
**Description of changes**
Started rewriting test_store.py script as code was outdated and not working anymore.
Rewriting is half way finished but not working yet. I think the created `idx` arrays are still not correct. So, don't merge yet.

### CODE REVIEW

**Comment by felix0097** [comment]
This works now. Does it have to pass `flake8`, because it didn't pass it before my changes? @davidsebfischer

**Comment by felix0097** [comment]
Output looks like this now:

[data_store_benchmark.pdf](https://github.com/theislab/sfaira/files/7704239/data_store_benchmark.pdf)

**Comment by davidsebfischer** [comment]
> This works now. Does it have to pass `flake8`, because it didn't pass it before my changes? @davidsebfischer

Let's fix the points from flake now:
```
 ./sfaira/data/utils_scripts/test_store.py:52:57: W291 trailing whitespace
./sfaira/data/utils_scripts/test_store.py:53:32: W291 trailing whitespace
./sfaira/data/utils_scripts/test_store.py:229:34: E712 comparison to False should be 'if cond is False:' or 'if not cond:'
./sfaira/data/utils_scripts/test_store.py:240:34: E712 comparison to True should be 'if cond is True:' or 'if cond:'
```

**Comment by felix0097** [comment]
This should be fine now:

[data_store_benchmark (3).pdf](https://github.com/theislab/sfaira/files/7720601/data_store_benchmark.3.pdf)

**Review by davidsebfischer — APPROVED** [review]
Thanks!

**Pull request merged**
