### PR TITLE
Cell type mapping csv files

### PR DESCRIPTION
**Pull request by davidsebfischer**
This branch collects the raw suggested csvs and harbors the moderated versions. I will merge this once we are done with all data sets. I will try to only have these csvs in the git diff to keep this annotation only. Moderated csvs (finshed annotation migration) are ticked below:

- [x] d10_1016_j_devcel_2020_01_033
- [x] d10_1038_s41586_019_1652_y
- [x] d10_1101_661728
- [x] d10_1016_j_cell_2017_09_004
- [x] d10_1038_nmeth_4407
- [x] d10_1038_s41586_020_2157_4
- [x] d10_1101_753806
- [x] d10_1016_j_cell_2018_02_001
- [x] d10_1038_s41422_018_0099_2
- [x] d10_1038_s41586_020_2922_4
- [x] d10_1126_science_aat5031
- [x] d10_1016_j_cell_2018_08_067
- [x] d10_1038_s41467_018_06318_7
- [x] d10_1038_s41590_020_0602_z
- [x] d10_1126_science_aay3224
- [x] d10_1016_j_cell_2019_06_029
- [x] d10_1038_s41467_019_10861_2
- [x] d10_1038_s41591_019_0468_5
- [x] d10_1186_s13059_019_1906_x
- [x] d10_1016_j_cell_2019_08_008
- [x] d10_1038_s41467_019_12464_3
- [x] d10_1038_s41593_019_0393_4´
- [x] d10_15252_embj_2018100811
- [x] d10_1016_j_celrep_2018_11_086
- [x] d10_1038_s41467_019_12780_8
- [x] d10_1038_s41597_019_0351_8
- [x] d_nan
- [x] d10_1016_j_cels_2016_08_011
- [x] d10_1038_s41586_018_0698_6
- [x] d10_1073_pnas_1914143116
- [x] d10_1016_j_cmet_2016_08_020
- [x] d10_1038_s41586_019_1373_2
- [x] d10_1084_jem_20191130
- [x] d10_1016_j_cmet_2019_01_021
- [x] d10_1038_s41586_019_1631_3
- [x] d10_1101_2020_03_13_991455

### CODE REVIEW

**Comment by le-ander** [comment]
@davidsebfischer done with hcl apart from "proliferating cells". not sure what to label those? unknown? (https://github.com/theislab/sfaira/blob/annotation_csvs/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2157_4/human_x_2020_microwellseq_han_x.tsv#L495)

**Comment by davidsebfischer** [comment]
> @davidsebfischer done with hcl apart from "proliferating cells". not sure what to label those? unknown? (https://github.com/theislab/sfaira/blob/annotation_csvs/sfaira/data/dataloaders/loaders/d10_1038_s41586_020_2157_4/human_x_2020_microwellseq_han_x.tsv#L495)

yes, unkown!

**Comment by le-ander** [comment]
Cool, and one other thing: when there was no specified progenitor cell label, I went with the termianl cell label.
i.e. I mapped "enterocyte progenitor cell" -> "enterocyte" rather than "enterocyte progenitor cell" -> "progenitor cell"

do you agree with that choice?

**Comment by davidsebfischer** [comment]
> do you agree with that choice?

yes! i did the same for MCA

**Comment by le-ander** [comment]
Awesome. everything done then :+1:

**Comment by davidsebfischer** [comment]
Wrote a unit test that checks all target cell types and that adds the CL IDs in post. This will make it easier for us to upgrade these maps to newer ontologies in the future.

**Pull request merged**
