### PR TITLE
Improve CLI documentation

### PR DESCRIPTION
**Pull request by davidsebfischer**

### CODE REVIEW

**Comment by davidsebfischer** [comment]
@Zethson could you check if the documentation here is valid now?

**Comment by Zethson** [comment]
> @Zethson could you check if the documentation here is valid now?

LGTM

**Comment by davidsebfischer** [comment]
I think the merged damaged some of the functionality we had before here.

**Comment by Zethson** [comment]
`Error: Invalid value for '--path-loader': Path 'sfaira/data/dataloaders/loaders/' does not exist.`

**Pull request merged**
