### PR TITLE
add model_id validation; closes #75

### LINKED ISSUE #75: Verify that the model_id of a zoo is valid
From my understanding the zoo attributes are inferred from the model_id.
However, if users create zoo objects with invalid/malformed model_ids this whole process may just break.

We should verify that a passed model_id to the constructor is valid and all required attributes can be extracted from it.

Raise an exception/User Warning or whatever is appropriate if not.

### PR DESCRIPTION
**Pull request by Zethson**
Signed-off-by: Zethson <lukas.heumos@posteo.net>

### CODE REVIEW

**Comment by Zethson** [comment]
Build crashes on Windows. GHA was down earlier so I think their CI may still be bonkers.

**Comment by davidsebfischer** [comment]
We mostly likely have issues with path handling on windows right now, too. In a couple of places, we use "/" to build up paths.

**Comment by Zethson** [comment]
> We mostly likely have issues with path handling on windows right now, too. In a couple of places, we use "/" to build up paths.

But that's not introduced with this PR, right?

**Comment by davidsebfischer** [comment]
No, that s already on dev!

**Comment by Zethson** [comment]
Do you want to merge this PR then? ;)

**Pull request merged**
