### PR TITLE
d10_1038_s41467_019_11036_9

### PR DESCRIPTION
**Pull request by johnmous**
This PR was created by the sfaira CLI adding dataset d10_1038_s41467_019_11036_9

### CODE REVIEW

**Comment by davidsebfischer** [comment]
Hi @johnmous! Thanks for the PR, this looks great! Did the CLI `test-dataloader` already pass? If so, the only point left to address would be the LINT check from the CI summary of this PR:

```
 ./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:6:1: F811 redefinition of unused 'scipy' from line 3
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:11:1: E302 expected 2 blank lines, found 1
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:14:43: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:14:45: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:15:30: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:15:32: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:15:50: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:15:52: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:38:49: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:38:51: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:38:66: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:38:68: E251 unexpected spaces around keyword / parameter equals
./data/dataloaders/loaders/d10_1038_s41467_019_11036_9/homosapiens_x_2019_x_fan_001.py:41:1: W293 blank line contains whitespace
```

**Comment by johnmous** [comment]
Hi @davidsebfischer . The test downloader did pass. I believe I fixed all the LINT points

**Comment by johnmous** [comment]
@davidsebfischer Can it be merged now?

**Comment by davidsebfischer** [comment]
> @davidsebfischer Can it be merged now?

Yes this looks great, thank you again!

**Comment by johnmous** [comment]
@davidsebfischer You are right, the  file is not available in GEO. I can make it available to you now through a download link, but it won't be permanent. Would that work for you?

**Comment by davidsebfischer** [comment]
Thanks for the quick response @johnmous, that's great! Would be great if you could send me a non permament download link, beyond that, could you let me know if this is annotation from the original authors of the study or secondard annotation? Feel free to email me under david dot fischer at helmholtz minus munich dot de as well.

**Pull request merged**
