### PR TITLE
Implementation of test-dataloader

### PR DESCRIPTION
**Pull request by Zethson**
Hi,

usage: `sfaira test-dataloader <path_to_sfaira> --doi <doi>`.
Example: `sfaira test-dataloader . --doi 10.1016.j.cmet.2019.01.021`

We need the path of sfaira to find the test and also since the test data is relative to the unit test python script.

### CODE REVIEW

**Comment by le-ander** [comment]
Awesome stuff @Zethson , this works very nicely!
One suggestion form my side: I think having to copy my datafiles into a cloned repo directory (`sfaira/unit_tests/template_data/`) feels wrong. I'd suggest, we stop using this folder and let the user provide the path to a folder with their data directly to the CLI command instead.

Thoughts? @Zethson @davidsebfischer

**Comment by Zethson** [comment]
+1 from my side.
If @davidsebfischer agrees I will implement the desired functionality

**Comment by davidsebfischer** [comment]
> I'd suggest, we stop using this folder and let the user provide the path to a folder with their data directly to the CLI command instead.

We could wrap this workflow with a final CLI call that takes this folder and a sfaira installation and copies it into the correct path?

**Comment by Zethson** [comment]
> > I'd suggest, we stop using this folder and let the user provide the path to a folder with their data directly to the CLI command instead.
> 
> We could wrap this workflow with a final CLI call that takes this folder and a sfaira installation and copies it into the correct path?

Tool installations are usually write protected. IMO it would be rather unforseen behavior if we did that and if something goes wrong the installations might be bonkers.

**Comment by davidsebfischer** [comment]
Can we finish on a print command that just tells the user where to copy this given an installation, e.g. via a command "prepare-branch"? Just so that they do not have to understand the full code.

**Comment by Zethson** [comment]
> Can we finish on a print command that just tells the user where to copy this given an installation, e.g. via a command "prepare-branch"? Just so that they do not have to understand the full code.

Sure, but I don't see much of a benefit. The path to copy it to would be rather ugly and still write protected if its an installation.
That's why we are currently not using the installation but rather the local sfaira clone to run the test. In any case they do not have to understand any code.

For simplicity and to adhere to KISS I would keep it this way. A path to the data sounds fine to me.

**Comment by Zethson** [comment]
`sfaira test-dataloader . --doi 10.1016.j.cmet.2019.01.021 --test-data /path/to/test_data` now works.
I tried to get rid of the path to Sfaira by working with the cwd, but ran into weird errors. Maybe another write permission issue. Since people adding datasets need to have a clone of sfaira anyways I think that it's totally fine if we just keep the path parameter.

I'd say it's ready to merge.

**Pull request merged**
