### PR TITLE
Adjust data loaders to directory-wise set-up

### PR DESCRIPTION
**Pull request by davidsebfischer**

### CODE REVIEW

**Comment by davidsebfischer** [comment]
Let's integrate this script https://github.com/theislab/sfaira/blob/master/sfaira/data/download_scripts/get_and_preprocess_HumanCellLandscape.ipynb into the hcl base loader https://github.com/theislab/sfaira/blob/5f3ec99c6571e24b85767be00613aad60f783980/sfaira/data/databases/template_dataloaders/hcl.py _load_hcl(). this is in line with #44.

**Comment by michalk8** [comment]
Hi @davidsebfischer ,
while I was browsing for some tutorials for sfaira, I've stumbled upon this PR and noticed the huge number of fields you have for e.g. the `DatasetBase`. Not sure if you've considered it, but here's a super useful library that can help with the field definition (like validation/conversion etc.): https://pypi.org/project/attrs/ (like more advanced version of Python's [dataclasses](https://docs.python.org/3/library/dataclasses.html)). Maybe it will be helpful.

**Comment by davidsebfischer** [comment]
@michalk8 thanks a lot for referencing `attrs`! I was not aware of that! Is your idea to declare `DatasetBase`as `@attr.s` to not have to include the long constructor of this abstract class which sets all attributes as None or is there more changes to the inherting classes induced by that?

**Comment by michalk8** [comment]
Yes, that's the general idea. I've used in as e.g.:
```python

foo: bool = attr.ib(
        default=None,  # default value
        repr=False,  # don't include in the __repr__
        init=False,  # don't include them in __init__ method
        validator=attr.validators.optional(attr.validators.instance_of(bool)), ...]
        on_setattr=[attr.setters.validate, ...],  # could include the erasure/value checks - the FNs have the signature of (instance, attribute: attr.Attribute, new_value) and last value is use (afaik)
)
```
Think in this way, you could get rid of some of the few property getters/setters that only do the checking.

**Comment by michalk8** [comment]
Regarding inheritance, I don't think there's anything special you need to do - only to make sure that if the subclasses also have `attr` attributes, the subclass should also be decorated with `@attr.s`.

**Comment by davidsebfischer** [comment]
`._load()` of all loaders runs without error

**Pull request merged**
